name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    # Notify to slack when build and test succeeded
    - name: Slack success notification
    -　run: |
          curl -X POST --data-urlencode 'payload={
    　       "text": ":tada::tada::tada:${{github.repository}}: Build and Test succeeded！:tada::tada::tada:"
          }'
